addons:
  sonarcloud:
    organization: "incountry"

language: java
dist: trusty

before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0x219BD9C9
  - sudo apt-add-repository 'deb http://repos.azulsystems.com/ubuntu stable main'
  - sudo apt-get update -qq && sudo apt-get install zulu-${ZULU_JDK} -y
  - test -z "${ZULU_JDK}" || export JDK${ZULU_JDK}_HOME=/usr/lib/jvm/zulu-${ZULU_JDK}-amd64
  - unset _JAVA_OPTIONS

sudo: required

notifications:
  email: false

script:
  - test -d "${JDK8_HOME}" || export JDK6_HOME=$(jdk_switcher home openjdk8)
  - test -d "${JDK7_HOME}" || export JDK7_HOME=$(jdk_switcher home openjdk7)
  - test -z "${ZULU_JDK}" || export TRAVIS_JDK_VERSION=zulujdk${ZULU_JDK}
  - gradle test --rerun-tasks
  - gradle build --debug

matrix:
  fast_finish: true
  include:
  - jdk: openjdk7
    sudo: required
    env:
      - ZULU_JDK=7
  - jdk: openjdk8
    sudo: required
    env:
      - ZULU_JDK=8
