addons:
  sonarcloud:
    organization: "incountry"

cache:
  directories:
    - dependencyCheck
    - gradle-custom

language:
  java

jdk:
  - openjdk11

sudo: false

notifications:
  email: false


before_install:
  # for sonar test coverage metric
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then git fetch --no-tags https://github.com/incountry/sdk-java.git +refs/heads/$TRAVIS_BRANCH:refs/remotes/origin/$TRAVIS_BRANCH; fi
  # for using gradle 6.5 instead of default 5 in travis
  #  - echo $PWD
  - ls -d gradle-custom/*
  - if [ ! "$(ls -A gradle-custom)" ]; then while IFS='=' read -r key value; do key=$(echo $key | tr '.' '_'); eval ${key}=\${value}; done < "gradle/wrapper/gradle-wrapper.properties"; gradleUrl=$(echo ${distributionUrl} | tr -d \\); wget ${gradleUrl}; unzip -j gradle-6.5-bin.zip -d gradle-custom; fi
  #  - wget https://services.gradle.org/distributions/gradle-6.5-bin.zip
  #  - ls
  #  - echo $PWD
  #  - unzip gradle-6.5-bin.zip
  - ls
  - ls -d gradle-custom/*
#  - echo $PWD
#  - echo $PWD/gradle-6.5
  - export GRADLE_HOME=$PWD/gradle-custom
  - export PATH=$GRADLE_HOME/bin:$PATH
  #  - export GRADLE_HOME=/gradle-6.5
  #  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v



script:
  - gradle build jacocoTestReport sonarqube
  - gradle integrationTest
