addons:
  sonarcloud:
    organization: "incountry"

language:
  java

jdk:
  - openjdk11

sudo: false

notifications:
  email: false

before_install:
  # for sonar test coverage metric
  - git fetch --no-tags https://github.com/incountry/sdk-java.git +refs/heads/develop:refs/remotes/origin/develop
  - git fetch --no-tags https://github.com/incountry/sdk-java.git +refs/heads/master:refs/remotes/origin/master
  # for using gradle 6.5 instead of default 5 in travis
  - wget https://services.gradle.org/distributions/gradle-6.5-bin.zip
  - unzip -qq gradle-6.5-bin.zip
  - export GRADLE_HOME=$PWD/gradle-6.5
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v

script:
  - gradle build jacocoTestReport sonarqube
  - gradle integrationTest
