addons:
  sonarcloud:
    organization: "incountry"

cache:
  directories:
    - dependencyCheck
    - "gradle-container/"
#    - gradle-6.5

language:
  java

jdk:
  - openjdk11

sudo: false

notifications:
  email: false


before_install:
  # for sonar test coverage metric
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then git fetch --no-tags https://github.com/incountry/sdk-java.git +refs/heads/$TRAVIS_BRANCH:refs/remotes/origin/$TRAVIS_BRANCH; fi
  # for using gradle 6.5 instead of default 5 in travis
  #  getting 'distributionUrl'property with gradle url from gradle-wrapper.properties file
  - while IFS='=' read -r key value; do key=$(echo $key | tr '.' '_'); eval ${key}=\${value}; done < "gradle/wrapper/gradle-wrapper.properties"; gradleUrl=$(echo ${distributionUrl} | tr -d \\)
  # getting gradle zip file name
  - arr=(${gradleUrl//// })
  - gradleZipFile=${arr[${#arr[*]}-1]}
  # getting gradle directory name after unzipping
  - arr2=(${gradleZipFile//-bin/ })
  - gradleDirectory=$arr2
  # checking is gradle already exist, if not download it
#  - if [ ! "$(ls -A ${gradleDirectory})" ]; then wget ${gradleUrl}; unzip -qq ${gradleZipFile}; fi
#  - if [ -d "$PWD/gradle-container/$gradleDirectory" ]; then ; else fi
  - ls $PWD/gradle-container
  - ls
  - if [ -d "$PWD/gradle-container/$gradleDirectory" ]; then mv $PWD/gradle-container/$gradleDirectory $PWD; else wget ${gradleUrl}; unzip -qq ${gradleZipFile}; fi
  - export GRADLE_HOME=$PWD/${gradleDirectory}
  - export PATH=$GRADLE_HOME/bin:$PATH
  - echo ${GRADLE_HOME}
  - echo ${PATH}
  - gradle -v



#script:
#  - gradle build jacocoTestReport sonarqube
#  - gradle integrationTest

after_script:
  - ls
  - ls $PWD/gradle-container
  - rm -rf $PWD/gradle-container/*
  - mv $PWD/$gradleDirectory $PWD/gradle-container
  - ls $PWD/gradle-container
  - echo $gradleDirectory
#  - gradleDirectory