addons:
  sonarcloud:
    organization: "incountry"

cache:
  directories:
    - dependencyCheck
    - $HOME/gradle-6.5


language:
  java

jdk:
  - openjdk11

sudo: false

notifications:
  email: false

before_install:
  # for sonar test coverage metric
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then git fetch --no-tags https://github.com/incountry/sdk-java.git +refs/heads/$TRAVIS_BRANCH:refs/remotes/origin/$TRAVIS_BRANCH; fi
  # for using gradle 6.5 instead of default 5 in travis
  - wget https://services.gradle.org/distributions/gradle-6.5-bin.zip
  - unzip gradle-6.5-bin.zip
  - export GRADLE_HOME=$PWD/gradle-6.5
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v

script:
  - gradle build jacocoTestReport sonarqube
  - gradle integrationTest
