addons:
  sonarcloud:
    organization: "incountry"

language:
  java

jdk:
  - openjdk8

sudo: false

notifications:
  email: false

script:
  - gradle build --rerun-tasks
  - gradle dependencyCheckAnalyze
  - gradle sonarqube