addons:
  sonarcloud:
    organization: "incountry"

language:
  java

jdk:
  - openjdk11
node_js: 12.16

sudo: false

notifications:
  email: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - gradle-container

before_install:
  # Switch to newer NodeJS to prevent SNYK scan issues
  - nvm install v12.16.0
  - nvm use v12.16.0
  # Get used Gradle version and download URL from file 'gradle-wrapper.properties'
  - while IFS='=' read -r key value; do key=$(echo $key | tr '.' '_'); eval ${key}=\${value}; done < "gradle/wrapper/gradle-wrapper.properties"; gradleUrl=$(echo ${distributionUrl} | tr -d \\)
  # Get gradle zip file name and gradle directory name
  - arr=(${gradleUrl//// }); gradleZipFile=${arr[${#arr[*]}-1]}
  - arr2=(${gradleZipFile//-bin/ }); gradleDirectory=$arr2
  # Check if Gradle binaries exist. If not, download them
  - if [ -d "$PWD/gradle-container/$gradleDirectory" ]; then mv $PWD/gradle-container/$gradleDirectory $PWD; else wget -q ${gradleUrl}; unzip -qq ${gradleZipFile}; fi
  - export GRADLE_HOME=$PWD/${gradleDirectory}; export PATH=$GRADLE_HOME/bin:$PATH
  # install latest JVM
  - wget -q https://download.java.net/java/GA/jdk16.0.1/7147401fd7354114ac51ef3e1328291f/9/GPL/openjdk-16.0.1_linux-x64_bin.tar.gz
  - tar -xf openjdk-16.0.1_linux-x64_bin.tar.gz
  - ls
  - export JAVA_HOME=$PWD/jdk-16.0.1

jobs:
  include:
    - stage: build
      name: "Build the code, scan with Snyk, run tests & Sonar"
      script:
        # Print debug information
        - echo "Building for branch=$TRAVIS_BRANCH, PR=${TRAVIS_PULL_REQUEST} ..."; env | grep "COMMIT\|PULL\|BRANCH"
        # Perform the build
        - ./travis-build.sh
        # move custom Gradle binaries to the cache
        - rm -rf $PWD/gradle-container/*
        - mv $PWD/$gradleDirectory $PWD/gradle-container
    - stage: build
      name: "Run integration tests"
      script:
        - gradle integrationTest

stages:
  - name: build

env:
  global:
    - APP_NAME=sdk-java
