addons:
  sonarcloud:
    organization: "incountry"

language:
  java

jdk:
  - openjdk8
  - Oracle JDK 11

sudo: false

notifications:
  email: false

script:
  - gradle test --rerun-tasks
  - gradle sonarqube