/*
 * InCountry
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2019-02-06T17:07:37Z
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.incountry.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * Data
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-02-06T12:08:15.253-05:00[America/Detroit]")public class Data {

  @SerializedName("custid")
  private String custid = null;

  @SerializedName("rowid")
  private String rowid = null;

  @SerializedName("blob")
  private String blob = null;

  @SerializedName("key1")
  private String key1 = null;

  @SerializedName("key2")
  private String key2 = null;

  @SerializedName("key3")
  private String key3 = null;

  @SerializedName("key4")
  private String key4 = null;

  @SerializedName("key5")
  private String key5 = null;
  public Data custid(String custid) {
    this.custid = custid;
    return this;
  }

  

  /**
  * Get custid
  * @return custid
  **/
  @Schema(required = true, description = "")
  public String getCustid() {
    return custid;
  }
  public void setCustid(String custid) {
    this.custid = custid;
  }
  public Data rowid(String rowid) {
    this.rowid = rowid;
    return this;
  }

  

  /**
  * Get rowid
  * @return rowid
  **/
  @Schema(description = "")
  public String getRowid() {
    return rowid;
  }
  public void setRowid(String rowid) {
    this.rowid = rowid;
  }
  public Data blob(String blob) {
    this.blob = blob;
    return this;
  }

  

  /**
  * Get blob
  * @return blob
  **/
  @Schema(required = true, description = "")
  public String getBlob() {
    return blob;
  }
  public void setBlob(String blob) {
    this.blob = blob;
  }
  public Data key1(String key1) {
    this.key1 = key1;
    return this;
  }

  

  /**
  * Get key1
  * @return key1
  **/
  @Schema(description = "")
  public String getKey1() {
    return key1;
  }
  public void setKey1(String key1) {
    this.key1 = key1;
  }
  public Data key2(String key2) {
    this.key2 = key2;
    return this;
  }

  

  /**
  * Get key2
  * @return key2
  **/
  @Schema(description = "")
  public String getKey2() {
    return key2;
  }
  public void setKey2(String key2) {
    this.key2 = key2;
  }
  public Data key3(String key3) {
    this.key3 = key3;
    return this;
  }

  

  /**
  * Get key3
  * @return key3
  **/
  @Schema(description = "")
  public String getKey3() {
    return key3;
  }
  public void setKey3(String key3) {
    this.key3 = key3;
  }
  public Data key4(String key4) {
    this.key4 = key4;
    return this;
  }

  

  /**
  * Get key4
  * @return key4
  **/
  @Schema(description = "")
  public String getKey4() {
    return key4;
  }
  public void setKey4(String key4) {
    this.key4 = key4;
  }
  public Data key5(String key5) {
    this.key5 = key5;
    return this;
  }

  

  /**
  * Get key5
  * @return key5
  **/
  @Schema(description = "")
  public String getKey5() {
    return key5;
  }
  public void setKey5(String key5) {
    this.key5 = key5;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Data data = (Data) o;
    return Objects.equals(this.custid, data.custid) &&
        Objects.equals(this.rowid, data.rowid) &&
        Objects.equals(this.blob, data.blob) &&
        Objects.equals(this.key1, data.key1) &&
        Objects.equals(this.key2, data.key2) &&
        Objects.equals(this.key3, data.key3) &&
        Objects.equals(this.key4, data.key4) &&
        Objects.equals(this.key5, data.key5);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(custid, rowid, blob, key1, key2, key3, key4, key5);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Data {\n");
    
    sb.append("    custid: ").append(toIndentedString(custid)).append("\n");
    sb.append("    rowid: ").append(toIndentedString(rowid)).append("\n");
    sb.append("    blob: ").append(toIndentedString(blob)).append("\n");
    sb.append("    key1: ").append(toIndentedString(key1)).append("\n");
    sb.append("    key2: ").append(toIndentedString(key2)).append("\n");
    sb.append("    key3: ").append(toIndentedString(key3)).append("\n");
    sb.append("    key4: ").append(toIndentedString(key4)).append("\n");
    sb.append("    key5: ").append(toIndentedString(key5)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
