/*
 * InCountry
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2019-01-15T16:20:14Z
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.incountry.api;

import com.incountry.api.ApiException;
import com.incountry.model.Data;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deletePostTest(String country, String rowid) throws ApiException {
        Data response = api.deletePost(country, rowid);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void keylookupPostTest(String country, String key2, String key3, String key4, String key5, String key1) throws ApiException {
        Data response = api.keylookupPost(country, key2, key3, key4, key5, key1);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void lookupPostTest(String country, String key2, String key3, String key4, String key5, String key1) throws ApiException {
        Data response = api.lookupPost(country, key2, key3, key4, key5, key1);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readPostTest(String country, String rowid) throws ApiException {
        Data response = api.readPost(country, rowid);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void writePostTest(String country, String rowid, String blob, String key1, String key2, String key3, String key4, String key5) throws ApiException {
        Data response = api.writePost(country, rowid, blob, key1, key2, key3, key4, key5);

        // TODO: test validations
    }
}
